name: ecommerse_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.7
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.14.4
  flutter_stripe: ^11.5.0
  flutter_svg: ^2.0.10+1
  get_it: ^8.2.0
  google_sign_in: ^6.2.2
  http: ^1.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true
  assets:
  - assets/svg/
  - assets/png/
 
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/logo.png"