// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUQXvDHlQVvWS3u_7S7Ln82SczvPlEcs4',
    appId: '1:470088447467:web:3a4ff01997aa8eb84c15ae',
    messagingSenderId: '470088447467',
    projectId: 'messageapp-459c7',
    authDomain: 'messageapp-459c7.firebaseapp.com',
    databaseURL: 'https://messageapp-459c7.firebaseio.com',
    storageBucket: 'messageapp-459c7.firebasestorage.app',
    measurementId: 'G-PHZ6CNWFZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtE5aMNmZWfdPLAK5FR7ZIETytnet9rJc',
    appId: '1:470088447467:android:b45a11e3d057ac3a4c15ae',
    messagingSenderId: '470088447467',
    projectId: 'messageapp-459c7',
    databaseURL: 'https://messageapp-459c7.firebaseio.com',
    storageBucket: 'messageapp-459c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_wulk3Am5f9-fqv8kqnHOF4teLsuFhC0',
    appId: '1:470088447467:ios:7b415985e8ecf9054c15ae',
    messagingSenderId: '470088447467',
    projectId: 'messageapp-459c7',
    databaseURL: 'https://messageapp-459c7.firebaseio.com',
    storageBucket: 'messageapp-459c7.firebasestorage.app',
    iosClientId: '470088447467-bsv547hv5rr3ktr7k50esijdp98u6shl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerseApp',
  );
}
