class AppStrings {
  static const String processingPayment = "Processing your payment...";
  static const String paymentSuccessful = "Payment Successful!";
  static const String paymentSuccessMessage = "Thank you for your purchase. Your order is being processed.";
  static const String backToHome = "Back to Home";
  static const String paymentFailed = "Payment Failed";
  static const String tryAgain = "Try Again";
  static const String itemAddedToCart = "Item added to cart!";
  static const String forgotPassword = "Forgot Password?";
  static const String login = "Login";
  static const String signUp = "Sign Up";
  static const String welcomeBack = "Welcome Back!";
  static const String loginToAccount = "Login to your account";
  static const String dontHaveAccount = "Don't have an account?";
  static const String checkout = "Checkout";
  static const String subTotal = "Sub-total";
  static const String deliveryFee = "Delivery Fee";
  static const String totalCost = "Total Cost";
  static const String addToCart = "Add to Cart";
  static const String description = "Description";
  static const String size = "Size";
  static const String menu = "Menu";
  static const String signOut = "Sign Out";
  static const String eShop = "E-Shop";
  static const String details = "Details";
  static const String error = "Error";
  static const String unableToLoadProducts = "Unable to load products.";
  static const String somethingWentWrongCart = "Something went wrong with your cart.";
}
