// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerse_app/test/unit/cart_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:ecommerse_app/features/domain/entities/cart.dart' as _i2;
import 'package:ecommerse_app/features/domain/entities/cart_product.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCart_1 extends _i1.SmartFake implements _i2.Cart {
  _FakeCart_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Cart].
///
/// See the documentation for Mockito's code generation for more information.
class MockCart extends _i1.Mock implements _i2.Cart {
  @override
  int get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  DateTime get date => (super.noSuchMethod(
        Invocation.getter(#date),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#date),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.getter(#date),
        ),
      ) as DateTime);

  @override
  List<_i3.CartProduct> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i3.CartProduct>[],
        returnValueForMissingStub: <_i3.CartProduct>[],
      ) as List<_i3.CartProduct>);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
        returnValueForMissingStub: <Object?>[],
      ) as List<Object?>);

  @override
  _i2.Cart copyWith({
    int? id,
    int? userId,
    DateTime? date,
    List<_i3.CartProduct>? products,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #id: id,
            #userId: userId,
            #date: date,
            #products: products,
          },
        ),
        returnValue: _FakeCart_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #userId: userId,
              #date: date,
              #products: products,
            },
          ),
        ),
        returnValueForMissingStub: _FakeCart_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #userId: userId,
              #date: date,
              #products: products,
            },
          ),
        ),
      ) as _i2.Cart);
}
